### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by greenm01** [mcantelon/node-mingy#3]
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: connect@1.6.4
npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
npm ERR! Actual:   {"npm":"1.0.27","node":"v0.5.5-pre"}

does not work with node trunk latest

**Comment by mcantelon** [comment]
Allo... thanks for the heads up... I've disabled the connect-dependent part of Mingy (which is experimental anyway) and republished to NPM.
